version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: always
    ports:
      - "443:443"
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/cloud/nginx/certs:/etc/nginx/certs
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /mnt/cloud/nginx/proxy:/etc/nginx/conf.d
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    network_mode: bridge
    container_name: letsencrypt
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
     - nginx-proxy
    restart: always
  pairingapi:
    image: 
